---
title: "Analysis"
author: "Sam Struthers- CSU ROSSyndicate"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("package_loader.R")
library(yardstick)
library(rpart)
library(randomForest)
set.seed(101)
```

# Load data

```{r}
corr <- read_rds("data/combined/correlated_data.rds")


corr_mod <- corr%>%
  dplyr::select(virridy_actual_cond:ross_turb, Turbidity:Field_Temp_C)%>%
    mutate(NO3_class = cut_number(NO3, n = 6))%>%
    select(-NO3, DTN)

train_corr <- sample_frac(corr_mod, size = .6)
test_corr <- corr_mod %>% anti_join(train_corr)


# 
#  NO3_cart <- rpart(NO3_class ~ ., data = train_corr,method = "class",  cp = 0.01)
#  
#  summary(NO3_cart)
# plot(NO3_cart)
# text(NO3_cart, cex = 0.8, use.n = TRUE, xpd = TRUE)
# 
# 
# test_corr$pred <- predict(NO3_cart, test_corr, type = 'class')
# 
# accuracy(test_corr, NO3_class, pred)

library()
no3_forest <- randomForest(NO3_class ~ ., data = train_corr)

#view the model output
(snow_forest)
#look at importance
importance(snow_forest)

```


